collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3994604
  brandStrength: 0.8864654
  rhythmicContrast: 0.01514891
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.4201792
typography_spectrum: 0.2161654
layout_spectrum: 0.9442356
name: Luvcraft
